/** DAY FLOW application bootstrap and UI orchestration. Business rules remain in services/engine. */
(function (root) {
  const DF = root.DayFlow;
  const priority = { low: 40, medium: 60, high: 80, 'very-high': 99, critical: 100 };
  const fieldData = form => Object.fromEntries(new FormData(form).entries());
  const node = (tag, className, text) => { const element = document.createElement(tag); if (className) element.className = className; if (text != null) element.textContent = text; return element; };
  const button = (label, action, className = 'btn btn-secondary') => { const element = node('button', className, label); element.type = 'button'; element.dataset.action = action; return element; };
  const formatMinutes = value => { const minutes = Math.max(0, Math.round(Number(value) || 0)); return minutes >= 60 ? `${Math.floor(minutes / 60)}h ${minutes % 60 ? `${minutes % 60}m` : ''}`.trim() : `${minutes}m`; };
  const notify = (message, error = false) => { const toast = node('div', `toast${error ? ' toast-error' : ''}`, message); toast.setAttribute('role', error ? 'alert' : 'status'); document.body.append(toast); setTimeout(() => toast.remove(), 4000); };

  DF.app = {
    onboardingStep: 1,
    historyMode: 'day',
    initialized: false,
    clockTimer: null,
    async init() {
      if (this.initialized) return true; DF.errors.install();
      try {
        await DF.storageService.init(); await DF.auth.restore(); DF.sync.init();
        DF.router.init(document.getElementById('app'), {
          guard: screen => !DF.auth.currentUser && !['login', 'signup'].includes(screen) ? 'login' : DF.auth.locked && screen !== 'lock' ? 'lock' : screen,
          onRoute: screen => this.render(screen),
          navigationTemplate: screen => DF.auth.currentUser && !['login', 'signup', 'lock', 'onboarding', 'history'].includes(screen) ? document.getElementById('template-bottom-nav').content.cloneNode(true) : null
        });
        document.addEventListener('click', event => this.handleAction(event).catch(error => notify(DF.errors.report(error, 'action').message, true)));
        document.addEventListener('submit', event => this.handleSubmit(event));
        document.addEventListener('input', event => { if (['task-search', 'task-filter'].includes(event.target.id)) this.renderTasks(); if (event.target.id === 'global-search') this.renderSearch(event.target.value); });
        document.addEventListener('change', event => { if (event.target.closest('#modal-settings')) this.saveSetting(event.target).catch(error => notify(DF.errors.report(error, 'settings').message, true)); });
        document.addEventListener('keydown', event => { if (event.key === 'Escape' && document.querySelector('.modal')) this.closeModal(); });
        const requested = location.hash.slice(1); const known = Object.prototype.hasOwnProperty.call(DF.router.routes, requested) ? requested : 'home'; const start = DF.auth.locked ? 'lock' : DF.auth.currentUser ? (DF.auth.currentUser.onboarded ? known : 'onboarding') : 'login';
        this.applyTheme(DF.auth.currentUser?.preferences?.theme); DF.router.navigate(start); this.initialized = true; DF.state.update({ initialized: true, loading: false });
        this.clockTimer = setInterval(() => this.updateClock(), 30000);
        if ('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('service-worker.js').catch(error => DF.errors.report(error, 'service worker registration'));
        return true;
      } catch (error) { DF.state.set('loading', false); DF.errors.renderFatal(error); return false; }
    },
    updateClock() { const target = document.querySelector('[data-current-time]'); if (target) target.textContent = new Date().toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }); },
    async handleAction(event) {
      const target = event.target.closest('[data-action], #fab-btn'); if (!target) return; event.preventDefault();
      if (target.id === 'fab-btn') { const current = document.getElementById('fab-menu'); if (current) current.remove(); else { document.body.append(document.getElementById('template-fab-menu').content.cloneNode(true)); document.querySelector('#fab-menu button')?.focus(); } return; }
      const action = target.dataset.action;
      const routes = { 'show-login': 'login', 'show-signup': 'signup', 'show-home': 'home', 'show-today': 'today', 'show-tasks': 'tasks', 'show-habits': 'habits', 'show-goals': 'goals', 'show-insights': 'insights', 'show-history': 'history' };
      if (routes[action]) return DF.router.navigate(routes[action]);
      if (['add-task', 'add-activity'].includes(action)) return this.openModal('template-modal-task', modal => { modal.querySelector('[name=date]').value = DF.dates.dateKey(DF.state.get('selectedDate')); if (action === 'add-activity') modal.querySelector('h2').textContent = 'Add Activity'; });
      if (action === 'add-habit') return this.openModal('template-modal-habit');
      if (['add-event', 'add-appointment'].includes(action)) return this.openModal('template-modal-event', modal => { modal.querySelector('[name=date]').value = DF.dates.dateKey(DF.state.get('selectedDate')); if (action === 'add-appointment') modal.querySelector('h2').textContent = 'Add Appointment'; });
      if (action === 'add-goal') return this.openModal('template-modal-goal');
      if (action === 'show-profile') return this.openProfile();
      if (action === 'show-settings') { this.closeModal(); return this.openSettings(); }
      if (action === 'close-modal') return this.closeModal();
      if (action === 'logout') { DF.auth.logout(); this.closeModal(); return DF.router.navigate('login'); }
      if (action === 'lock-app') { DF.auth.lock(); this.closeModal(); return DF.router.navigate('lock'); }
      if (action === 'previous-day' || action === 'next-day') { DF.state.set('selectedDate', DF.dates.addDays(DF.state.get('selectedDate'), action === 'next-day' ? 1 : -1)); return this.renderToday(); }
      if (['history-day', 'history-week', 'history-month'].includes(action)) { this.historyMode = action.split('-')[1]; return this.renderHistory(); }
      if (action === 'regenerate-day' || action === 'replan-day') return this.replanDay('MANUAL_REPLAN');
      if (action === 'im-late' || action === 'im-early') { const amount = DF.validation.number(prompt(`How many minutes ${action === 'im-late' ? 'late' : 'early'}?`, '15'), { min: 1, max: 240, fallback: 15 }); const now = new Date(Date.now() + amount * 60000 * (action === 'im-late' ? 1 : -1)); return this.replanDay(action === 'im-late' ? 'LATE' : 'EARLY', now); }
      if (['start-current', 'pause-current', 'complete-current', 'need-more-time', 'finished-early', 'skip-current', 'cant-do-current'].includes(action)) return this.liveAction(action, target.dataset.id);
      if (action === 'export-backup') { const backup = await DF.backup.create(); const passphrase = prompt('Optional: enter a passphrase (8+ characters) to encrypt this backup. Leave blank for plain JSON.'); return DF.backup.download(passphrase ? await DF.backup.encrypt(backup, passphrase) : backup); }
      if (action === 'import-backup') return this.importBackup();
      if (action === 'reset-app' && confirm('Delete all DAY FLOW data on this device?')) { await DF.db.clearAll(); DF.auth.logout(); this.closeModal(); return DF.router.navigate('signup'); }
      if (action === 'complete-task' || action === 'complete-habit') return this.completeItem(target.dataset.id, action.endsWith('task') ? 'tasks' : 'habits');
      if (action === 'delete-task' || action === 'delete-habit') return this.deleteItem(target.dataset.id, action.endsWith('task') ? 'tasks' : 'habits');
      if (action === 'complete-goal' || action === 'delete-goal') return this.updateGoal(target.dataset.id, action === 'complete-goal');
    },
    async handleSubmit(event) {
      event.preventDefault(); const form = event.target; const data = fieldData(form);
      try {
        if (form.id === 'signup-form') { if (data.password !== data.confirm) throw new Error('Passwords do not match'); await DF.auth.signup(data); DF.router.navigate('onboarding'); }
        else if (form.id === 'login-form') { await DF.auth.login(data.email, data.password, Boolean(form.rememberMe?.checked)); DF.router.navigate(DF.auth.currentUser.onboarded ? 'home' : 'onboarding'); }
        else if (form.id === 'unlock-form') { await DF.auth.unlock(data.password); DF.router.navigate('home'); }
        else if (form.id === 'task-form') { await DF.tasks.save(new DF.Task({ userId: DF.auth.requireUser().id, title: DF.validation.required(data.title, 'Title'), description: DF.validation.sanitize(data.description), duration: DF.validation.number(data.duration, { min: 5, max: 480, fallback: 30 }), dueDate: data.date, category: data.category.toUpperCase(), priority: priority[data.priority] || 60, type: data.type, preferredTime: data.preferredTime, availableFrom: data.availableFrom, availableUntil: data.availableUntil })); this.closeModal(); await this.generatePlan(true, 'ITEM_ADDED'); DF.router.navigate('tasks'); }
        else if (form.id === 'habit-form') { const targetDays = [...form.querySelectorAll('[name=targetDays]:checked')].map(x => Number(x.value)); const routineItems = String(data.routineItems || '').split('\n').map((line, index) => { const [title, duration, requirement] = line.split('|').map(value => value.trim()); return title ? { id: String(index), title: DF.validation.sanitize(title), duration: DF.validation.number(duration, { min: 5, max: 180, fallback: 10 }), required: requirement.toLowerCase() !== 'optional' } : null; }).filter(Boolean); await DF.habits.save(new DF.Habit({ userId: DF.auth.requireUser().id, title: DF.validation.required(data.title, 'Name'), description: DF.validation.sanitize(data.description), duration: DF.validation.number(data.duration, { min: 5, max: 240, fallback: 30 }), frequency: data.frequency, preferredTime: data.preferredTime, targetDays, routineItems })); this.closeModal(); await this.generatePlan(true, 'ROUTINE_ADDED'); DF.router.navigate('habits'); }
        else if (form.id === 'event-form') { if (DF.dates.timeToMinutes(data.endTime) <= DF.dates.timeToMinutes(data.startTime)) throw new Error('Event end time must be after its start time'); await DF.events.save(new DF.Event({ userId: DF.auth.requireUser().id, title: DF.validation.required(data.title, 'Title'), date: data.date, startTime: data.startTime, endTime: data.endTime, bufferBefore: DF.validation.number(data.bufferBefore, { min: 0, max: 120 }), bufferAfter: DF.validation.number(data.bufferAfter, { min: 0, max: 120 }) })); this.closeModal(); await this.generatePlan(true, 'FIXED_COMMITMENT_ADDED'); DF.router.navigate('home'); }
        else if (form.id === 'goal-form') { await DF.goals.save(new DF.Goal({ userId: DF.auth.requireUser().id, title: DF.validation.required(data.title, 'Goal'), deadline: data.deadline, weeklyTargetMinutes: DF.validation.number(data.weeklyTargetMinutes, { min: 15, max: 2400, fallback: 150 }), sessionMinutes: DF.validation.number(data.sessionMinutes, { min: 5, max: 240, fallback: 30 }), preferredTime: data.preferredTime })); this.closeModal(); await this.generatePlan(true, 'GOAL_ADDED'); DF.router.navigate('goals'); }
        else if (form.id === 'profile-form') { const user = DF.auth.requireUser(); const name = DF.validation.required(data.name, 'Name'); const email = String(data.email || '').trim().toLowerCase(); const occupation = DF.validation.sanitize(data.occupation); const workDays = [...form.querySelectorAll('[name=profileWorkDays]:checked')].map(input => Number(input.value)); if (!DF.validation.email(email)) throw new Error('Enter a valid email address'); const users = await DF.users.getAll(); if (users.some(account => account.id !== user.id && String(account.email).toLowerCase() === email)) throw new Error('An account with that email already exists'); if (users.some(account => account.id !== user.id && String(account.name).toLowerCase() === name.toLowerCase())) throw new Error('Choose a different account name'); Object.assign(user, { name, email, occupation, preferences: { ...user.preferences, workDays, workLabel: occupation || 'Work / School', wakeTime: data.wakeTime, sleepTime: data.sleepTime, workStart: data.workStart, workEnd: data.workEnd, lunchStart: data.lunchStart, lunchEnd: data.lunchEnd, commuteMinutes: DF.validation.number(data.commuteMinutes, { min: 0, max: 180 }) } }); DF.auth.currentUser = await DF.users.save(user); this.closeModal(); await this.generatePlan(true, 'SCHEDULE_UPDATED'); notify('Profile and schedule saved'); }
      } catch (error) { notify(error.message, true); }
    },
    render(screen) { this.markNavigation(screen); if (screen === 'onboarding') this.setupOnboarding(); else if (screen === 'home') this.renderHome(); else if (screen === 'today') this.renderToday(); else if (screen === 'tasks') this.renderTasks(); else if (screen === 'habits') this.renderHabits(); else if (screen === 'goals') this.renderGoals(); else if (screen === 'insights') this.renderInsights(); else if (screen === 'history') this.renderHistory(); },
    markNavigation(screen) { document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.action === `show-${screen}`)); },
    setupOnboarding() { this.onboardingStep = 1; const next = document.getElementById('onboard-next'); const prev = document.getElementById('onboard-prev'); const show = () => { document.querySelectorAll('.onboarding-step').forEach(x => x.style.display = Number(x.dataset.step) === this.onboardingStep ? '' : 'none'); document.querySelector('.current-step').textContent = this.onboardingStep; document.querySelector('.onboarding-progress .progress-fill').style.width = `${this.onboardingStep / 8 * 100}%`; prev.style.display = this.onboardingStep > 1 ? '' : 'none'; next.textContent = this.onboardingStep === 8 ? 'Build my first flow' : 'Next'; }; prev.onclick = () => { this.onboardingStep--; show(); }; next.onclick = async () => { if (this.onboardingStep < 8) { this.onboardingStep++; show(); return; } await this.finishOnboarding(); }; show(); },
    async finishOnboarding() { const user = DF.auth.requireUser(); const get = name => document.querySelector(`[name=${name}]`); user.name = get('name')?.value || user.name; user.occupation = get('occupation')?.value || ''; const workDays = [...document.querySelectorAll('[name=workDays]:checked')].map(input => Number(input.value)); user.preferences = { ...user.preferences, wakeTime: get('wakeTime')?.value || '07:00', sleepTime: get('sleepTime')?.value || '22:00', morningMinutes: DF.validation.number(get('morningMinutes')?.value, { min: 10, max: 180, fallback: 45 }), workDays, workStart: get('workStart')?.value || '09:00', workEnd: get('workEnd')?.value || '17:00', lunchStart: get('lunchStart')?.value || '12:00', lunchEnd: get('lunchEnd')?.value || '13:00', commuteMinutes: DF.validation.number(get('commuteMinutes')?.value, { min: 0, max: 180 }), workLabel: user.occupation || 'Work / School', autoSchedule: get('autoSchedule')?.checked ?? true, notifications: get('notifications')?.checked ?? false, smartSuggestions: get('smartSuggestions')?.checked ?? true, theme: get('theme')?.value || 'system' }; user.onboarded = true; DF.auth.currentUser = await DF.users.save(user); const wake = DF.dates.timeToMinutes(user.preferences.wakeTime); const sleep = DF.dates.timeToMinutes(user.preferences.sleepTime); const presets = { 'drink-water': { duration: 5, type: 'OPTIONAL', priority: 20, preferredTime: DF.dates.minutesToTime(wake + 10) }, exercise: { duration: 40, type: 'FLEXIBLE', priority: 60, preferredTime: '18:00' }, read: { duration: 30, type: 'OPTIONAL', priority: 30, preferredTime: '20:00' }, 'sleep-on-time': { duration: 15, type: 'SEMI_FIXED', priority: 80, preferredTime: DF.dates.minutesToTime(sleep - 15), availableUntil: user.preferences.sleepTime }, walk: { duration: 20, type: 'OPTIONAL', priority: 30, preferredTime: '18:00' }, stretch: { duration: 10, type: 'SEMI_FIXED', priority: 45, preferredTime: DF.dates.minutesToTime(wake + 15) }, meditate: { duration: 10, type: 'FLEXIBLE', priority: 50, preferredTime: DF.dates.minutesToTime(wake + 20) } }; const defaults = [...document.querySelectorAll('[name=defaultHabits]:checked')]; for (const input of defaults) await DF.habits.save(new DF.Habit({ userId: user.id, title: input.nextElementSibling.textContent.trim().replace(/^\S+\s/, ''), ...presets[input.value] })); await this.generatePlan(true, 'ONBOARDING'); DF.router.navigate('home'); },
    async planInput(date) { const user = DF.auth.requireUser(); return { date, tasks: await DF.tasks.forUser(user.id), habits: await DF.habits.forDate(user.id, date), events: await DF.events.forDate(user.id, date), goals: await DF.goals.forUser(user.id), history: await DF.activityLogs.forUser(user.id), preferences: user.preferences }; },
    async generatePlan(force = false, trigger = 'INITIAL_PLAN', now = new Date()) { const user = DF.auth.requireUser(); const date = DF.state.get('selectedDate'); const existing = await DF.plans.forDate(user.id, date); if (existing && !force) return existing; const input = await this.planInput(date); let plan; if (existing && force) { plan = DF.schedulerEngine.reschedule({ ...input, existingPlan: existing, now, trigger }); } else plan = DF.schedulerEngine.generate({ ...input, trigger }); plan.userId = user.id; if (existing && !plan.previousVersionId) { plan.previousVersionId = existing.id; plan.version = existing.version + 1; } const saved = await DF.plans.save(plan); if (user.preferences.notifications) DF.notifications.schedule(saved); return saved; },
    async replanDay(trigger, now = new Date()) { this.closeModal(); const plan = await this.generatePlan(true, trigger, now); notify(plan.changeSummary?.message || 'Your day has been replanned.'); return DF.router.navigate('home'); },
    async liveAction(action, itemId) { const plan = await DF.plans.forDate(DF.auth.requireUser().id, new Date()); const moment = plan && DF.dailyFlow.moment(plan); const id = itemId || moment?.active?.id; if (!id) throw new Error('There is no current activity to update.'); const map = { 'start-current': 'START', 'pause-current': 'PAUSE', 'complete-current': 'COMPLETE', 'need-more-time': 'MORE_TIME', 'finished-early': 'FINISHED_EARLY', 'skip-current': 'SKIP', 'cant-do-current': 'CANT_DO' }; const result = await DF.dailyFlow.perform({ userId: DF.auth.requireUser().id, itemId: id, action: DF.constants.FLOW_ACTION[map[action]], date: new Date() }); if (result.requiresReplan) return this.replanDay(map[action]); notify(`${result.item.title} ${result.item.status.toLowerCase()}.`); return this.renderHome(); },
    async renderHome() { const user = DF.auth.requireUser(); const now = new Date(); const hour = now.getHours(); document.querySelector('[data-greeting]').textContent = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'; document.querySelector('[data-user-name]').textContent = user.name; document.querySelector('[data-selected-date]').textContent = DF.dates.formatDate(now, { weekday: 'long', month: 'long', day: 'numeric' }); this.updateClock(); const plan = await this.generatePlan(); const moment = DF.dailyFlow.moment(plan, now); await this.renderCurrent(document.querySelector('[data-current-item]'), moment.active, plan, now); this.renderNext(document.querySelector('[data-next-item]'), moment.next); this.renderScheduleList(document.querySelector('[data-up-next]'), moment.upcoming, 'Nothing else is scheduled. Enjoy the open space.'); for (const [name, value] of Object.entries({ scheduled: formatMinutes(moment.scheduledMinutes), free: formatMinutes(moment.freeMinutes), important: moment.important, warnings: moment.warnings })) document.querySelector(`[data-day-metric=${name}]`).textContent = value; const notice = document.querySelector('[data-flow-notice]'); const summary = plan.changeSummary; notice.hidden = !summary && !plan.unscheduled.length; if (summary) notice.textContent = `${summary.message} ${summary.moved.length ? `Moved: ${summary.moved.map(x => x.title).join(', ')}.` : ''}`; else if (plan.unscheduled.length) notice.textContent = `${plan.unscheduled.length} activit${plan.unscheduled.length === 1 ? 'y' : 'ies'} could not realistically fit today.`; },
    async renderCurrent(container, item, plan, now) { container.replaceChildren(); if (!item) { const empty = node('div', 'empty-state'); empty.append(node('strong', '', 'You have open time right now.'), node('p', '', 'Add an activity or ask DAY FLOW to rebuild the remaining day.'), button('Add activity', 'add-activity', 'btn btn-primary')); container.append(empty); return; } const log = await DF.activityLogs.forPlanItem(DF.auth.requireUser().id, plan.id, item.sourceId); const current = now.getHours() * 60 + now.getMinutes(); const elapsed = Math.max(0, current - DF.dates.timeToMinutes(item.startTime)); const remaining = Math.max(0, DF.dates.timeToMinutes(item.endTime) - current); const progress = Math.min(100, Math.round(elapsed / Math.max(1, item.duration) * 100)); const top = node('div', 'current-meta'); top.append(node('span', `type-badge type-${item.type.toLowerCase()}`, item.type.replace('_', ' ')), node('span', 'text-secondary', `${formatMinutes(remaining)} remaining`)); const title = node('h3', 'activity-title', item.title); const times = node('p', 'activity-time', `Planned ${DF.dates.formatTime(item.startTime)}–${DF.dates.formatTime(item.endTime)} · ${formatMinutes(item.duration)}`); const actual = node('p', 'text-secondary text-sm', log?.actualStart ? `Actual start ${new Date(log.actualStart).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}${log.actualDuration ? ` · ${formatMinutes(log.actualDuration)}` : ''}` : 'Actual time begins when you press Start.'); const bar = node('div', 'progress-bar-small'); const fill = node('div', 'progress-fill'); fill.style.width = `${progress}%`; bar.append(fill); const actions = node('div', 'live-actions'); const definitions = item.status === 'STARTED' ? [['Pause', 'pause-current'], ['Complete', 'complete-current'], ['More time', 'need-more-time'], ['Can’t do this', 'cant-do-current']] : [['Start', 'start-current'], ['Complete', 'complete-current'], ['Skip', 'skip-current'], ['Replan', 'replan-day']]; for (const [label, action] of definitions) { const control = button(label, action, action === 'start-current' || action === 'complete-current' ? 'btn btn-primary' : 'btn btn-secondary'); control.dataset.id = item.id; actions.append(control); } container.append(top, title, times, actual, bar, actions); document.querySelector('[data-current-status]').textContent = item.status; },
    renderNext(container, item) { container.replaceChildren(); if (!item) { container.append(node('div', 'empty-state compact', 'No next activity—your remaining time is open.')); return; } const card = node('article', 'next-card'); const body = node('div'); body.append(node('strong', '', item.title), node('p', 'text-secondary text-sm', `${DF.dates.formatTime(item.startTime)} · ${formatMinutes(item.duration)} · ${item.type.replace('_', ' ')}`)); card.append(body, node('span', 'next-time', DF.dates.formatTime(item.startTime))); container.append(card); },
    async renderToday() { const date = DF.state.get('selectedDate'); document.querySelector('[data-date-strip]').textContent = DF.dates.dateKey(date) === DF.dates.dateKey() ? 'Today' : DF.dates.formatDate(date, { weekday: 'long', month: 'short', day: 'numeric' }); const plan = await this.generatePlan(); this.renderScheduleList(document.querySelector('[data-schedule-list]'), plan.items, 'Your day is empty. Add your first activity and DAY FLOW will start building your flow.'); const capacity = document.querySelector('[data-plan-capacity]'); capacity.textContent = plan.unscheduled.length ? `${plan.unscheduled.length} activit${plan.unscheduled.length === 1 ? 'y' : 'ies'} could not realistically fit. Review the reasons below.` : `${formatMinutes(plan.items.reduce((sum, item) => sum + item.duration, 0))} planned with ${formatMinutes(plan.freeWindows.reduce((sum, item) => sum + item.duration, 0))} available as free windows.`; const windows = document.querySelector('[data-free-windows]'); windows.replaceChildren(); if (!plan.freeWindows.length) windows.append(node('div', 'empty-state compact', 'No free window of 10 minutes or more.')); else for (const window of plan.freeWindows) windows.append(node('span', 'window-chip', `${DF.dates.formatTime(window.startTime)}–${DF.dates.formatTime(window.endTime)} · ${formatMinutes(window.duration)}`)); const reasons = document.querySelector('[data-plan-explanations]'); reasons.replaceChildren(); for (const explanation of [...plan.explanations.slice(0, 6), ...plan.unscheduled.map(item => ({ message: `${item.title}: ${item.explanation}` }))]) reasons.append(node('p', 'explanation', explanation.message)); },
    renderScheduleList(container, items, empty) { container.replaceChildren(); if (!items.length) { const state = node('div', 'empty-state'); state.append(node('strong', '', empty), button('Add activity', 'add-activity', 'btn btn-primary')); container.append(state); return; } for (const item of items) { const row = node('article', `schedule-item status-${item.status.toLowerCase()}`); const time = node('div', 'schedule-time', DF.dates.formatTime(item.startTime)); const details = node('div', 'schedule-details'); const heading = node('div', 'schedule-heading'); heading.append(node('strong', '', item.title), node('span', `type-dot type-${item.type.toLowerCase()}`, item.type.replace('_', ' '))); details.append(heading, node('small', 'text-secondary', `${DF.dates.formatTime(item.startTime)}–${DF.dates.formatTime(item.endTime)} · ${formatMinutes(item.duration)} · ${item.status}`), node('small', 'schedule-reason', item.reason || 'Scheduled in the available day.')); row.append(time, details); container.append(row); } },
    async renderSearch(query) { const target = document.querySelector('[data-search-results]'); const term = String(query || '').trim().toLowerCase(); target.replaceChildren(); target.hidden = term.length < 2; if (target.hidden) return; const user = DF.auth.requireUser(); const sources = [['Task', await DF.tasks.forUser(user.id)], ['Event', await DF.events.forUser(user.id)], ['Routine', await DF.habits.forUser(user.id)], ['Goal', await DF.goals.forUser(user.id)], ['History', await DF.activityLogs.forUser(user.id)]]; const matches = sources.flatMap(([kind, items]) => items.filter(item => String(item.title || '').toLowerCase().includes(term)).map(item => ({ kind, item }))).slice(0, 12); if (!matches.length) target.append(node('div', 'empty-state compact', 'Nothing matched your local DAY FLOW data.')); else for (const match of matches) target.append(node('div', 'search-result', `${match.kind} · ${match.item.title}`)); },
    async renderTasks() { const container = document.querySelector('[data-task-list]'); if (!container) return; const query = document.getElementById('task-search').value.toLowerCase(); const filter = document.getElementById('task-filter').value; let items = await DF.tasks.forUser(DF.auth.requireUser().id); items = items.filter(x => x.title.toLowerCase().includes(query) && (!filter || (filter === 'completed' ? x.status === 'COMPLETED' : filter === 'overdue' ? x.dueDate && x.dueDate < DF.dates.dateKey() && x.status !== 'COMPLETED' : filter === 'today' ? x.dueDate === DF.dates.dateKey() : x.category.toLowerCase() === filter))); this.renderEntityList(container, items, 'task'); },
    async renderHabits() { const container = document.querySelector('[data-habit-list]'); if (!container) return; this.renderEntityList(container, await DF.habits.forUser(DF.auth.requireUser().id), 'habit'); },
    async renderGoals() { const container = document.querySelector('[data-goal-list]'); const user = DF.auth.requireUser(); const [goals, logs] = await Promise.all([DF.goals.forUser(user.id), DF.activityLogs.forUser(user.id)]); const progress = new Map(DF.dailyFlow.insights({ logs, goals }).goalMinutes.map(goal => [goal.id, goal.minutes])); container.replaceChildren(); if (!goals.length) { const empty = node('div', 'empty-state'); empty.append(node('strong', '', 'No goals yet.'), node('p', '', 'Add a weekly target and DAY FLOW will reserve realistic sessions.')); container.append(empty); return; } for (const goal of goals) { const actual = progress.get(goal.id) || 0; const percent = Math.min(100, Math.round(actual / Math.max(1, goal.weeklyTargetMinutes) * 100)); const card = node('article', `entity-card goal-card${goal.status === 'COMPLETED' ? ' completed' : ''}`); const content = node('div', 'entity-content'); content.append(node('strong', '', goal.title), node('small', 'text-secondary', `${formatMinutes(actual)} of ${formatMinutes(goal.weeklyTargetMinutes)} this week · ${percent}%${goal.deadline ? ` · Due ${DF.dates.formatDate(goal.deadline)}` : ''}`)); const actions = node('div', 'entity-actions'); for (const [action, label] of [['complete-goal', '✓'], ['delete-goal', '×']]) { const control = button(label, action, `btn-icon${action === 'delete-goal' ? ' danger' : ''}`); control.dataset.id = goal.id; control.setAttribute('aria-label', `${action === 'complete-goal' ? 'Complete' : 'Delete'} ${goal.title}`); if (action === 'complete-goal' && goal.status === 'COMPLETED') control.disabled = true; actions.append(control); } card.append(content, actions); container.append(card); } },
    async renderInsights() { const user = DF.auth.requireUser(); const [logs, plans, goals, habits] = await Promise.all([DF.activityLogs.forUser(user.id), DF.plans.forUser(user.id), DF.goals.forUser(user.id), DF.habits.forUser(user.id)]); const insights = DF.dailyFlow.insights({ logs, plans, goals }); document.querySelector('[data-insight=completion]').textContent = `${insights.completionRate}%`; document.querySelector('[data-insight=variance]').textContent = `${insights.estimateVariance > 0 ? '+' : ''}${insights.estimateVariance}%`; document.querySelector('[data-insight=overloaded]').textContent = insights.overloadedDays; const goalList = document.querySelector('[data-goal-progress]'); goalList.replaceChildren(); if (!insights.goalMinutes.length) goalList.append(node('div', 'empty-state compact', 'Add a goal to track time invested.')); else for (const goal of insights.goalMinutes) goalList.append(node('div', 'entity-card', `${goal.title}: ${formatMinutes(goal.minutes)} of ${formatMinutes(goal.target)} this week`)); const observations = document.querySelector('[data-observations]'); observations.replaceChildren(); const learned = user.preferences.learningEnabled === false ? new Map() : DF.optimizer.observations(logs); if (!learned.size) observations.append(node('div', 'empty-state compact', user.preferences.learningEnabled === false ? 'Local learning is disabled in Preferences.' : 'Complete activities to build transparent local observations.')); else for (const [id, data] of [...learned].slice(0, 5)) { const title = logs.find(log => log.sourceId === id)?.title || 'Activity'; observations.append(node('p', 'explanation', `${title} usually takes about ${formatMinutes(data.averageDuration)} based on ${data.samples} record${data.samples === 1 ? '' : 's'}.`)); } const streaks = document.querySelector('[data-streak-list]'); streaks.replaceChildren(); const active = habits.map(habit => ({ title: habit.title, count: this.habitStreak(habit) })).filter(x => x.count); if (!active.length) streaks.append(node('div', 'empty-state compact', 'Complete routines to build a consistency history.')); else for (const streak of active) streaks.append(node('div', 'entity-card', `${streak.title}: ${streak.count} day streak`)); const chart = document.querySelector('[data-productivity-chart]'); chart.replaceChildren(); for (let offset = 6; offset >= 0; offset--) { const date = DF.dates.addDays(new Date(), -offset); const count = logs.filter(log => log.date === DF.dates.dateKey(date) && log.status === 'COMPLETED').length; const column = node('div', 'chart-column'); const bar = node('div', 'chart-bar'); bar.style.height = count ? `${Math.min(100, 8 + count * 18)}%` : '0'; bar.title = `${count} completed`; column.append(bar, node('small', '', DF.dates.formatDate(date, { weekday: 'narrow' }))); chart.append(column); } },
    async renderHistory() { const user = DF.auth.requireUser(); const [plans, logs] = await Promise.all([DF.plans.forUser(user.id), DF.activityLogs.forUser(user.id)]); document.querySelectorAll('.segmented button').forEach(control => control.classList.toggle('active', control.dataset.action === `history-${this.historyMode}`)); const today = new Date(); const range = this.historyMode === 'day' ? 1 : this.historyMode === 'week' ? 7 : 31; const dates = Array.from({ length: range }, (_, offset) => DF.dates.dateKey(DF.dates.addDays(today, -offset))); const relevantPlans = plans.filter(plan => dates.includes(plan.date)).sort((a, b) => b.date.localeCompare(a.date) || b.version - a.version); const relevantLogs = logs.filter(log => dates.includes(log.date)); const summary = document.querySelector('[data-history-summary]'); summary.textContent = `${relevantPlans.length} plan version${relevantPlans.length === 1 ? '' : 's'} · ${relevantLogs.filter(log => log.status === 'COMPLETED').length} completed · ${relevantLogs.filter(log => ['SKIPPED', 'MISSED'].includes(log.status)).length} skipped or missed`; const list = document.querySelector('[data-history-list]'); list.replaceChildren(); if (!relevantPlans.length) { list.append(node('div', 'empty-state', 'No saved plan history in this period.')); return; } for (const plan of relevantPlans) { const card = node('article', 'history-card'); card.append(node('div', 'history-card-title', `${DF.dates.formatDate(plan.date)} · Version ${plan.version}`), node('p', 'text-secondary text-sm', plan.changeSummary?.message || 'Original daily plan'), node('p', '', `${plan.items.length} scheduled · ${plan.unscheduled.length} deferred`)); list.append(card); } },
    habitStreak(habit) { const completed = new Set(habit.completions); let streak = 0; for (let date = new Date(); completed.has(DF.dates.dateKey(date)); date = DF.dates.addDays(date, -1)) streak++; return streak; },
    renderEntityList(container, items, kind) { container.replaceChildren(); if (!items.length) { const empty = node('div', 'empty-state'); empty.append(node('strong', '', kind === 'task' ? 'No tasks yet.' : 'No routines yet.'), node('p', '', kind === 'task' ? 'Add important work and DAY FLOW will find a realistic opening.' : 'Add a routine and its ordered steps will flow around fixed commitments.'), button(`Add ${kind === 'task' ? 'task' : 'routine'}`, kind === 'task' ? 'add-task' : 'add-habit', 'btn btn-primary')); container.append(empty); return; } const today = DF.dates.dateKey(); for (const item of items) { const done = kind === 'task' ? item.status === 'COMPLETED' : item.completions.includes(today); const card = node('article', `entity-card${done ? ' completed' : ''}`); const content = node('div', 'entity-content'); content.append(node('strong', '', item.title), node('small', 'text-secondary', kind === 'task' ? `${formatMinutes(item.duration)} · ${item.category} · ${item.type.replace('_', ' ')}` : `${item.routineItems.length || 1} step${item.routineItems.length === 1 ? '' : 's'} · ${item.frequency}`)); const actions = node('div', 'entity-actions'); const complete = button(done ? '✓' : '○', `complete-${kind}`, 'btn-icon'); complete.dataset.id = item.id; complete.disabled = done; complete.setAttribute('aria-label', `${done ? 'Completed' : 'Complete'} ${item.title}`); const remove = button('×', `delete-${kind}`, 'btn-icon danger'); remove.dataset.id = item.id; remove.setAttribute('aria-label', `Delete ${item.title}`); actions.append(complete, remove); card.append(content, actions); container.append(card); } },
    openModal(templateId, setup) { this.closeModal(); const fragment = document.getElementById(templateId).content.cloneNode(true); document.body.append(fragment); const modal = document.body.lastElementChild; const heading = modal.querySelector('h2'); modal.setAttribute('role', 'dialog'); modal.setAttribute('aria-modal', 'true'); if (heading) { heading.id ||= 'day-flow-modal-title'; modal.setAttribute('aria-labelledby', heading.id); } setup?.(modal); requestAnimationFrame(() => { modal.classList.add('open'); modal.querySelector('input, button, select, textarea')?.focus(); }); return modal; },
    closeModal() { document.querySelector('.modal')?.remove(); document.getElementById('fab-menu')?.remove(); },
    openProfile() { const modal = this.openModal('template-modal-profile'); const user = DF.auth.requireUser(); const values = { name: user.name, email: user.email, occupation: user.occupation, ...user.preferences }; for (const [key, value] of Object.entries(values)) { const field = modal.querySelector(`[name=${key}]`); if (field) field.value = value ?? ''; } modal.querySelectorAll('[name=profileWorkDays]').forEach(input => { input.checked = (user.preferences.workDays || []).map(Number).includes(Number(input.value)); }); },
    openSettings() { const modal = this.openModal('template-modal-settings'); const p = DF.auth.requireUser().preferences; for (const name of ['notifications', 'sound', 'vibration', 'autoSchedule', 'smartSuggestions', 'learningEnabled']) { const field = modal.querySelector(`[name=${name}]`); if (field) field.checked = Boolean(p[name]); } modal.querySelector('[name=theme]').value = p.theme || 'system'; modal.querySelector('[name=bufferMinutes]').value = p.bufferMinutes || 0; },
    async saveSetting(field) { const user = DF.auth.requireUser(); const value = field.type === 'checkbox' ? field.checked : field.type === 'number' ? Number(field.value) : field.value; user.preferences = { ...user.preferences, [field.name]: value }; DF.auth.currentUser = await DF.users.save(user); if (field.name === 'theme') this.applyTheme(value); if (field.name === 'notifications' && value) await DF.notifications.request(); notify('Setting saved'); },
    applyTheme(theme = 'system') { document.documentElement.dataset.theme = theme; },
    async completeItem(id, store) { const repo = DF[store]; const user = DF.auth.requireUser(); const item = await repo.get(id); DF.access.assert(item, user.id); if (store === 'tasks') item.status = 'COMPLETED'; else if (!item.completions.includes(DF.dates.dateKey())) item.completions.push(DF.dates.dateKey()); await repo.save(item); const plan = await DF.plans.forDate(user.id, new Date()); const planned = plan?.items.find(entry => entry.sourceId === id || entry.routineId === id); await DF.activityLogs.save(new DF.ActivityLog({ userId: user.id, planId: plan?.id || '', sourceId: id, source: store === 'tasks' ? 'task' : 'routine', title: item.title, date: DF.dates.dateKey(), plannedStart: planned?.startTime || '', plannedEnd: planned?.endTime || '', plannedDuration: planned?.duration || item.duration, actualDuration: 0, status: 'COMPLETED', reason: 'Marked complete outside Live Flow; actual duration was not measured.' })); await this.generatePlan(true, 'ITEM_COMPLETED'); store === 'tasks' ? this.renderTasks() : this.renderHabits(); },
    async deleteItem(id, store) { const repo = DF[store]; const item = await repo.get(id); DF.access.assert(item, DF.auth.requireUser().id); if (!confirm(`Delete “${item.title}”?`)) return; await repo.delete(id); await this.generatePlan(true, 'ITEM_REMOVED'); store === 'tasks' ? this.renderTasks() : this.renderHabits(); },
    async updateGoal(id, complete) { const goal = await DF.goals.get(id); DF.access.assert(goal, DF.auth.requireUser().id); if (complete) { goal.status = 'COMPLETED'; goal.progress = 100; await DF.goals.save(goal); } else if (confirm(`Delete “${goal.title}”?`)) await DF.goals.delete(id); await this.generatePlan(true, complete ? 'GOAL_COMPLETED' : 'GOAL_REMOVED'); await this.renderGoals(); },
    importBackup() { const input = document.createElement('input'); input.type = 'file'; input.accept = 'application/json'; input.onchange = async () => { try { if (!input.files?.[0]) return; let backup = JSON.parse(await input.files[0].text()); if (backup.format === 'day-flow-encrypted-backup') { const passphrase = prompt('Enter the backup passphrase'); if (!passphrase) return; backup = await DF.backup.decrypt(backup, passphrase); } DF.backup.validate(backup); if (!confirm('Restore this backup? Existing DAY FLOW data on this device will be replaced.')) return; await DF.backup.restore(backup, { confirmed: true }); await DF.auth.restore(); notify('Backup restored'); this.closeModal(); DF.router.navigate(DF.auth.currentUser ? 'home' : 'login'); } catch (error) { notify(error.message, true); } }; input.click(); }
  };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', () => DF.app.init()); else DF.app.init();
})(globalThis);
