/**
 * Application Bootstrap
 * Entry point, initialization, main app orchestration
 */

(function (root) {
  const DF = root.DayFlow;
  const priority = { low: 40, medium: 60, high: 80 };
  const fieldData = form => Object.fromEntries(new FormData(form).entries());
  const node = (tag, className, text) => { const element = document.createElement(tag); if (className) element.className = className; if (text != null) element.textContent = text; return element; };
  const notify = (message, error = false) => { const toast = node('div', `toast${error ? ' toast-error' : ''}`, message); document.body.append(toast); setTimeout(() => toast.remove(), 3500); };

  DF.app = {
    onboardingStep: 1,
    initialized: false,
    async init() {
      if (this.initialized) return true;
      DF.errors.install();
      try {
        await DF.storageService.init(); await DF.auth.restore(); DF.sync.init();
        DF.router.init(document.getElementById('app'), {
          guard: screen => !DF.auth.currentUser && !['login', 'signup'].includes(screen) ? 'login' : DF.auth.locked && screen !== 'lock' ? 'lock' : screen,
          onRoute: screen => this.render(screen),
          navigationTemplate: screen => DF.auth.currentUser && !['login', 'signup', 'lock', 'onboarding'].includes(screen) ? document.getElementById('template-bottom-nav').content.cloneNode(true) : null
        });
        document.addEventListener('click', event => this.handleAction(event).catch(error => notify(DF.errors.report(error, 'action').message, true))); document.addEventListener('submit', event => this.handleSubmit(event)); document.addEventListener('input', event => { if (event.target.id === 'task-search' || event.target.id === 'task-filter') this.renderTasks(); }); document.addEventListener('change', event => { if (event.target.closest('#modal-settings')) this.saveSetting(event.target).catch(error => notify(DF.errors.report(error, 'settings').message, true)); });
        const start = DF.auth.locked ? 'lock' : DF.auth.currentUser ? (DF.auth.currentUser.onboarded ? (location.hash.slice(1) || 'home') : 'onboarding') : 'login'; this.applyTheme(DF.auth.currentUser?.preferences?.theme); DF.router.navigate(start); this.initialized = true; DF.state.update({ initialized: true, loading: false });
        if ('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('service-worker.js').catch(error => DF.errors.report(error, 'service worker registration'));
        return true;
      } catch (error) { DF.state.set('loading', false); DF.errors.renderFatal(error); return false; }
    },
    async handleAction(event) {
      const target = event.target.closest('[data-action], #fab-btn'); if (!target) return; event.preventDefault();
      if (target.id === 'fab-btn') { const current = document.getElementById('fab-menu'); if (current) current.remove(); else document.body.append(document.getElementById('template-fab-menu').content.cloneNode(true)); return; }
      const action = target.dataset.action;
      const routes = { 'show-login': 'login', 'show-signup': 'signup', 'show-home': 'home', 'show-today': 'today', 'show-tasks': 'tasks', 'show-habits': 'habits', 'show-goals': 'goals', 'show-insights': 'insights' };
      if (routes[action]) return DF.router.navigate(routes[action]);
      if (action === 'add-task') return this.openModal('template-modal-task', modal => { modal.querySelector('[name=date]').value = DF.dates.dateKey(DF.state.get('selectedDate')); });
      if (action === 'add-habit') return this.openModal('template-modal-habit');
      if (action === 'add-event') return this.openModal('template-modal-event', modal => { modal.querySelector('[name=date]').value = DF.dates.dateKey(DF.state.get('selectedDate')); });
      if (action === 'add-goal') return this.openModal('template-modal-goal');
      if (action === 'show-profile') return this.openProfile();
      if (action === 'show-settings') { this.closeModal(); return this.openSettings(); }
      if (action === 'close-modal') return this.closeModal();
      if (action === 'logout') { DF.auth.logout(); this.closeModal(); return DF.router.navigate('login'); }
      if (action === 'lock-app') { DF.auth.lock(); this.closeModal(); return DF.router.navigate('lock'); }
      if (action === 'previous-day' || action === 'next-day') { DF.state.set('selectedDate', DF.dates.addDays(DF.state.get('selectedDate'), action === 'next-day' ? 1 : -1)); return this.renderToday(); }
      if (action === 'regenerate-day') return this.generatePlan(true);
      if (action === 'export-backup') { const backup = await DF.backup.create(); const passphrase = prompt('Optional: enter a passphrase (8+ characters) to encrypt this backup. Leave blank for plain JSON.'); return DF.backup.download(passphrase ? await DF.backup.encrypt(backup, passphrase) : backup); }
      if (action === 'import-backup') return this.importBackup();
      if (action === 'reset-app' && confirm('Delete all DAY FLOW data on this device?')) { await DF.db.clearAll(); DF.auth.logout(); this.closeModal(); return DF.router.navigate('signup'); }
      if (action === 'complete-task' || action === 'complete-habit') return this.completeItem(target.dataset.id, action.endsWith('task') ? 'tasks' : 'habits');
      if (action === 'delete-task' || action === 'delete-habit') return this.deleteItem(target.dataset.id, action.endsWith('task') ? 'tasks' : 'habits');
      if (action === 'complete-goal' || action === 'delete-goal') return this.updateGoal(target.dataset.id, action === 'complete-goal');
    },
    async handleSubmit(event) {
      event.preventDefault(); const form = event.target; const data = fieldData(form);
      try {
        if (form.id === 'signup-form') { if (data.password !== data.confirm) throw new Error('Passwords do not match'); await DF.auth.signup(data); DF.router.navigate('onboarding'); }
        else if (form.id === 'login-form') { await DF.auth.login(data.email, data.password, Boolean(form.rememberMe?.checked)); DF.router.navigate(DF.auth.currentUser.onboarded ? 'home' : 'onboarding'); }
        else if (form.id === 'unlock-form') { await DF.auth.unlock(data.password); DF.router.navigate('home'); }
        else if (form.id === 'task-form') { await DF.tasks.save(new DF.Task({ userId: DF.auth.requireUser().id, title: DF.validation.required(data.title, 'Title'), description: DF.validation.sanitize(data.description), duration: DF.validation.number(data.duration, { min: 5, max: 480, fallback: 30 }), dueDate: data.date, category: data.category.toUpperCase(), priority: priority[data.priority] || 60 })); this.closeModal(); await this.generatePlan(true); DF.router.navigate('tasks'); }
        else if (form.id === 'habit-form') { const targetDays = [...form.querySelectorAll('[name=targetDays]:checked')].map(x => Number(x.value)); await DF.habits.save(new DF.Habit({ userId: DF.auth.requireUser().id, title: DF.validation.required(data.title, 'Name'), description: DF.validation.sanitize(data.description), duration: DF.validation.number(data.duration, { min: 5, max: 240, fallback: 30 }), frequency: data.frequency, preferredTime: data.preferredTime, targetDays })); this.closeModal(); await this.generatePlan(true); DF.router.navigate('habits'); }
        else if (form.id === 'event-form') { if (DF.dates.timeToMinutes(data.endTime) <= DF.dates.timeToMinutes(data.startTime)) throw new Error('Event end time must be after its start time'); await DF.events.save(new DF.Event({ userId: DF.auth.requireUser().id, title: DF.validation.required(data.title, 'Title'), date: data.date, startTime: data.startTime, endTime: data.endTime })); this.closeModal(); await this.generatePlan(true); DF.router.navigate('today'); }
        else if (form.id === 'goal-form') { await DF.goals.save(new DF.Goal({ userId: DF.auth.requireUser().id, title: DF.validation.required(data.title, 'Goal'), deadline: data.deadline })); this.closeModal(); DF.router.navigate('goals'); }
        else if (form.id === 'profile-form') { const user = DF.auth.requireUser(); Object.assign(user, { name: data.name, email: data.email, occupation: data.occupation, preferences: { ...user.preferences, wakeTime: data.wakeTime, sleepTime: data.sleepTime, workStart: data.workStart, workEnd: data.workEnd, lunchStart: data.lunchStart, lunchEnd: data.lunchEnd, commuteMinutes: Number(data.commuteMinutes || 0) } }); DF.auth.currentUser = await DF.users.save(user); this.closeModal(); notify('Profile saved'); }
      } catch (error) { notify(error.message, true); }
    },
    render(screen) { this.markNavigation(screen); if (screen === 'onboarding') this.setupOnboarding(); else if (screen === 'home') this.renderHome(); else if (screen === 'today') this.renderToday(); else if (screen === 'tasks') this.renderTasks(); else if (screen === 'habits') this.renderHabits(); else if (screen === 'goals') this.renderGoals(); else if (screen === 'insights') this.renderInsights(); },
    markNavigation(screen) { document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.action === `show-${screen}`)); },
    setupOnboarding() { this.onboardingStep = 1; const next = document.getElementById('onboard-next'); const prev = document.getElementById('onboard-prev'); const show = () => { document.querySelectorAll('.onboarding-step').forEach(x => x.style.display = Number(x.dataset.step) === this.onboardingStep ? '' : 'none'); document.querySelector('.current-step').textContent = this.onboardingStep; document.querySelector('.onboarding-progress .progress-fill').style.width = `${this.onboardingStep / 8 * 100}%`; prev.style.display = this.onboardingStep > 1 ? '' : 'none'; next.textContent = this.onboardingStep === 8 ? 'Start my day' : 'Next'; }; prev.onclick = () => { this.onboardingStep--; show(); }; next.onclick = async () => { if (this.onboardingStep < 8) { this.onboardingStep++; show(); return; } await this.finishOnboarding(); }; show(); },
    async finishOnboarding() { const user = DF.auth.requireUser(); const get = name => document.querySelector(`[name=${name}]`); user.name = get('name')?.value || user.name; user.occupation = get('occupation')?.value || ''; user.preferences = { ...user.preferences, wakeTime: get('wakeTime')?.value || '07:00', sleepTime: get('sleepTime')?.value || '22:00', workStart: get('workStart')?.value || '09:00', workEnd: get('workEnd')?.value || '17:00', autoSchedule: get('autoSchedule')?.checked ?? true, notifications: get('notifications')?.checked ?? false }; user.onboarded = true; DF.auth.currentUser = await DF.users.save(user); const defaults = [...document.querySelectorAll('[name=defaultHabits]:checked')]; for (const input of defaults) await DF.habits.save(new DF.Habit({ userId: user.id, title: input.nextElementSibling.textContent.trim().replace(/^\S+\s/, '') })); await this.generatePlan(true); DF.router.navigate('home'); },
    async generatePlan(force = false) { const user = DF.auth.requireUser(); const date = DF.state.get('selectedDate'); const existing = await DF.plans.forDate(user.id, date); if (existing && !force) return existing; const input = { date, tasks: await DF.tasks.forUser(user.id), habits: await DF.habits.forDate(user.id, date), events: await DF.events.forDate(user.id, date), history: await DF.activityLogs.forUser(user.id), preferences: user.preferences }; const plan = existing && force && DF.dates.dateKey(date) === DF.dates.dateKey() ? DF.schedulerEngine.reschedule({ ...input, existingPlan: existing, now: new Date() }) : DF.schedulerEngine.generate(input); plan.id = existing?.id || plan.id; plan.userId = user.id; plan.version = (existing?.version || 0) + 1; const saved = await DF.plans.save(plan); if (user.preferences.notifications) DF.notifications.schedule(saved); return saved; },
    async renderHome() { const user = DF.auth.requireUser(); const now = new Date(); const hour = now.getHours(); document.querySelector('[data-greeting]').textContent = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'; document.querySelector('[data-user-name]').textContent = user.name; document.querySelector('[data-selected-date]').textContent = DF.dates.formatDate(now, { weekday: 'long', month: 'long', day: 'numeric' }); const plan = await this.generatePlan(); const currentMinutes = now.getHours() * 60 + now.getMinutes(); const current = plan.items.find(x => DF.dates.timeToMinutes(x.startTime) <= currentMinutes && DF.dates.timeToMinutes(x.endTime) > currentMinutes); const upcoming = plan.items.filter(x => DF.dates.timeToMinutes(x.startTime) > currentMinutes).slice(0, 3); const card = document.querySelector('[data-current-item]'); card.querySelector('.activity-title').textContent = current?.title || 'No activity scheduled'; card.querySelector('.activity-time').textContent = current ? `${DF.dates.formatTime(current.startTime)} – ${DF.dates.formatTime(current.endTime)}` : 'Free time'; this.renderScheduleList(document.querySelector('[data-up-next]'), upcoming, 'No upcoming activities'); const tasks = await DF.tasks.forUser(user.id); const habits = await DF.habits.forUser(user.id); const progress = { tasks: [tasks.filter(x => x.status === 'COMPLETED').length, tasks.length], habits: [habits.filter(x => x.completions.includes(DF.dates.dateKey())).length, habits.length], schedule: [plan.items.filter(x => x.status === 'COMPLETED').length, plan.items.length] }; for (const [kind, [done, total]] of Object.entries(progress)) { const count = document.querySelector(`[data-progress-count=${kind}]`); count.textContent = done; count.nextElementSibling.textContent = `/${total}`; } },
    async renderToday() { const date = DF.state.get('selectedDate'); document.querySelector('[data-date-strip]').textContent = DF.dates.dateKey(date) === DF.dates.dateKey() ? 'Today' : DF.dates.formatDate(date, { weekday: 'long', month: 'short', day: 'numeric' }); const plan = await this.generatePlan(); const container = document.querySelector('[data-schedule-list]'); this.renderScheduleList(container, plan.items, 'No activities scheduled'); if (plan.unscheduled.length) { container.append(node('h3', 'section-title', 'Could not fit')); for (const item of plan.unscheduled) container.append(node('div', 'entity-card', `${item.title} — ${item.reason === 'UNMET_DEPENDENCY' ? 'waiting for a dependency' : 'no available time'}`)); } },
    renderScheduleList(container, items, empty) { container.replaceChildren(); if (!items.length) { container.append(node('div', 'empty-state', empty)); return; } for (const item of items) { const row = node('article', 'schedule-item'); const time = node('div', 'schedule-time', DF.dates.formatTime(item.startTime)); const details = node('div', 'schedule-details'); details.append(node('strong', '', item.title), node('small', 'text-secondary', `${DF.dates.formatTime(item.startTime)} – ${DF.dates.formatTime(item.endTime)}`)); row.append(time, details); container.append(row); } },
    async renderTasks() { const container = document.querySelector('[data-task-list]'); if (!container) return; const query = document.getElementById('task-search').value.toLowerCase(); const filter = document.getElementById('task-filter').value; let items = await DF.tasks.forUser(DF.auth.requireUser().id); items = items.filter(x => x.title.toLowerCase().includes(query) && (!filter || (filter === 'completed' ? x.status === 'COMPLETED' : filter === 'overdue' ? x.dueDate && x.dueDate < DF.dates.dateKey() && x.status !== 'COMPLETED' : filter === 'today' ? x.dueDate === DF.dates.dateKey() : x.category.toLowerCase() === filter))); this.renderEntityList(container, items, 'task'); },
    async renderHabits() { const container = document.querySelector('[data-habit-list]'); if (!container) return; this.renderEntityList(container, await DF.habits.forUser(DF.auth.requireUser().id), 'habit'); },
    async renderGoals() { const container = document.querySelector('[data-goal-list]'); const goals = await DF.goals.forUser(DF.auth.requireUser().id); container.replaceChildren(); if (!goals.length) { container.append(node('div', 'empty-state', 'No goals yet')); return; } for (const goal of goals) { const card = node('article', `entity-card${goal.status === 'COMPLETED' ? ' completed' : ''}`); const content = node('div', 'entity-content'); content.append(node('strong', '', goal.title), node('small', 'text-secondary', goal.deadline ? `Due ${DF.dates.formatDate(goal.deadline)}` : 'No deadline')); const actions = node('div', 'entity-actions'); for (const [action, label] of [['complete-goal', '✓'], ['delete-goal', '×']]) { const button = node('button', `btn-icon${action === 'delete-goal' ? ' danger' : ''}`, label); button.dataset.action = action; button.dataset.id = goal.id; button.setAttribute('aria-label', `${action === 'complete-goal' ? 'Complete' : 'Delete'} ${goal.title}`); if (action === 'complete-goal' && goal.status === 'COMPLETED') button.disabled = true; actions.append(button); } card.append(content, actions); container.append(card); } },
    async renderInsights() { const user = DF.auth.requireUser(); const tasks = await DF.tasks.forUser(user.id); const habits = await DF.habits.forUser(user.id); const logs = await DF.activityLogs.forUser(user.id); const percent = (done, total) => `${total ? Math.round(done / total * 100) : 0}%`; document.querySelector('[data-insight=tasks]').textContent = percent(tasks.filter(x => x.status === 'COMPLETED').length, tasks.length); const habitTargets = habits.reduce((sum, habit) => sum + habit.completions.length, 0); document.querySelector('[data-insight=habits]').textContent = percent(habitTargets, Math.max(habits.length * 7, habitTargets)); document.querySelector('[data-insight=schedule]').textContent = percent(logs.filter(x => x.status === 'COMPLETED').length, logs.length); const streaks = document.querySelector('[data-streak-list]'); streaks.replaceChildren(); const active = habits.map(habit => ({ title: habit.title, count: this.habitStreak(habit) })).filter(x => x.count); if (!active.length) streaks.append(node('div', 'empty-state', 'Complete habits to build a streak')); else for (const streak of active) streaks.append(node('div', 'entity-card', `${streak.title}: ${streak.count} day streak`)); const chart = document.querySelector('[data-productivity-chart]'); chart.replaceChildren(); for (let offset = 6; offset >= 0; offset--) { const date = DF.dates.addDays(new Date(), -offset); const count = logs.filter(log => log.date === DF.dates.dateKey(date) && log.status === 'COMPLETED').length; const column = node('div', 'chart-column'); const bar = node('div', 'chart-bar'); bar.style.height = `${Math.min(100, 10 + count * 18)}%`; bar.title = `${count} completed`; column.append(bar, node('small', '', DF.dates.formatDate(date, { weekday: 'narrow' }))); chart.append(column); } },
    habitStreak(habit) { const completed = new Set(habit.completions); let streak = 0; for (let date = new Date(); completed.has(DF.dates.dateKey(date)); date = DF.dates.addDays(date, -1)) streak++; return streak; },
    renderEntityList(container, items, kind) { container.replaceChildren(); if (!items.length) { container.append(node('div', 'empty-state', `No ${kind}s yet`)); return; } const today = DF.dates.dateKey(); for (const item of items) { const done = kind === 'task' ? item.status === 'COMPLETED' : item.completions.includes(today); const card = node('article', `entity-card${done ? ' completed' : ''}`); const content = node('div', 'entity-content'); content.append(node('strong', '', item.title), node('small', 'text-secondary', kind === 'task' ? `${item.duration} min · ${item.category}` : `${item.duration} min · ${item.frequency}`)); const actions = node('div', 'entity-actions'); const complete = node('button', 'btn-icon', done ? '✓' : '○'); complete.dataset.action = `complete-${kind}`; complete.dataset.id = item.id; complete.disabled = done; complete.setAttribute('aria-label', `${done ? 'Completed' : 'Complete'} ${item.title}`); const remove = node('button', 'btn-icon danger', '×'); remove.dataset.action = `delete-${kind}`; remove.dataset.id = item.id; remove.setAttribute('aria-label', `Delete ${item.title}`); actions.append(complete, remove); card.append(content, actions); container.append(card); } },
    openModal(templateId, setup) { this.closeModal(); const fragment = document.getElementById(templateId).content.cloneNode(true); document.body.append(fragment); const modal = document.body.lastElementChild; setup?.(modal); requestAnimationFrame(() => modal.classList.add('open')); return modal; },
    closeModal() { document.querySelector('.modal')?.remove(); document.getElementById('fab-menu')?.remove(); },
    openProfile() { const modal = this.openModal('template-modal-profile'); const user = DF.auth.requireUser(); const values = { name: user.name, email: user.email, occupation: user.occupation, ...user.preferences }; for (const [key, value] of Object.entries(values)) { const field = modal.querySelector(`[name=${key}]`); if (field) field.value = value ?? ''; } },
    openSettings() { const modal = this.openModal('template-modal-settings'); const p = DF.auth.requireUser().preferences; for (const name of ['notifications', 'sound', 'vibration', 'autoSchedule', 'smartSuggestions']) { const field = modal.querySelector(`[name=${name}]`); if (field) field.checked = Boolean(p[name]); } modal.querySelector('[name=theme]').value = p.theme || 'system'; },
    async saveSetting(field) { const user = DF.auth.requireUser(); const value = field.type === 'checkbox' ? field.checked : field.value; user.preferences = { ...user.preferences, [field.name]: value }; DF.auth.currentUser = await DF.users.save(user); if (field.name === 'theme') this.applyTheme(value); if (field.name === 'notifications' && value) await DF.notifications.request(); notify('Setting saved'); },
    applyTheme(theme = 'system') { document.documentElement.dataset.theme = theme; },
    async completeItem(id, store) { const repo = DF[store]; const user = DF.auth.requireUser(); const item = await repo.get(id); DF.access.assert(item, user.id); if (store === 'tasks') item.status = 'COMPLETED'; else if (!item.completions.includes(DF.dates.dateKey())) item.completions.push(DF.dates.dateKey()); await repo.save(item); const plan = await DF.plans.forDate(user.id, new Date()); const planned = plan?.items.find(entry => entry.sourceId === id); await DF.activityLogs.save(new DF.ActivityLog({ userId: user.id, planId: plan?.id || '', sourceId: id, source: store === 'tasks' ? 'task' : 'habit', title: item.title, date: DF.dates.dateKey(), plannedStart: planned?.startTime || '', plannedEnd: planned?.endTime || '', actualEnd: new Date().toISOString(), actualDuration: planned?.duration || item.duration, status: 'COMPLETED' })); await this.generatePlan(true); store === 'tasks' ? this.renderTasks() : this.renderHabits(); },
    async deleteItem(id, store) { const repo = DF[store]; const item = await repo.get(id); DF.access.assert(item, DF.auth.requireUser().id); if (!confirm(`Delete “${item.title}”?`)) return; await repo.delete(id); await this.generatePlan(true); store === 'tasks' ? this.renderTasks() : this.renderHabits(); },
    async updateGoal(id, complete) { const goal = await DF.goals.get(id); DF.access.assert(goal, DF.auth.requireUser().id); if (complete) { goal.status = 'COMPLETED'; goal.progress = 100; await DF.goals.save(goal); } else if (confirm(`Delete “${goal.title}”?`)) await DF.goals.delete(id); await this.renderGoals(); },
    importBackup() { const input = document.createElement('input'); input.type = 'file'; input.accept = 'application/json'; input.onchange = async () => { try { let backup = JSON.parse(await input.files[0].text()); if (backup.format === 'day-flow-encrypted-backup') { const passphrase = prompt('Enter the backup passphrase'); if (!passphrase) return; backup = await DF.backup.decrypt(backup, passphrase); } DF.backup.validate(backup); if (!confirm('Restore this backup? Existing DAY FLOW data on this device will be replaced.')) return; await DF.backup.restore(backup, { confirmed: true }); await DF.auth.restore(); notify('Backup restored'); this.closeModal(); DF.router.navigate(DF.auth.currentUser ? 'home' : 'login'); } catch (error) { notify(error.message, true); } }; input.click(); }
  };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', () => DF.app.init()); else DF.app.init();
})(globalThis);
